//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_S2016_MidTerm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int TodoID { get; set; }
        public string TodoName { get; set; }
        public string TodoNotes { get; set; }
        public Nullable<bool> Completed { get; set; }
    }
}
